version: '3'
services: 
  db:
    build: ./mssql
    environment: 
      - SA_PASSWORD="yourStrong(!)Password"
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1401:1433"
    container_name: mssql
    hostname: mssql
    volumes: 
      - ./mssql/mssqldata:/var/opt/mssql/data